<a href="https://colab.research.google.com/github/py-ram/git-basics/blob/main/02_Masai_School_Python_Working_With_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
# Using regular Python lists
list1 = [1, 2, 3, 4, 5]
list2 = [10, 20, 30, 40, 50]

# What happens if we try to add them?
result = list1 + list2
print(result)
# Output: [1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
# This CONCATENATES the lists, not element-wise addition!

# To do element-wise addition with lists, we need a loop:
result = []
for i in range(len(list1)):
    result.append(list1[i] + list2[i])
print(result)
# Output: [11, 22, 33, 44, 55]

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11, 22, 33, 44, 55]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
result = arr1 * arr2
print(result)

[ 10  40  90 160 250]


In [ ]:
print(type(arr1*2))

<class 'numpy.ndarray'>


In [ ]:
print(arr1*2)

[ 2  4  6  8 10]


# Create diffwrent arrays

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Built in Fucnitons

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
zeros_2d = np.zeros((3, 4, 6))

In [ ]:
print(zeros_2d)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [ ]:
zeros_2d.shape

(3, 4, 6)

In [ ]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full_array = np.full((2, 3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]]


In [ ]:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
list1 = [1, 2, 3]
print(list1)

[1, 2, 3]


In [ ]:
arr = np.array([1, 2, 3.4])
print(arr)

[1.  2.  3.4]


In [ ]:
list1 = [1, 2, 3.4]
print(list1)

[1, 2, 3.4]


In [ ]:
arr = np.array([1, 2, "hello"])
print(arr)

['1' '2' 'hello']


In [ ]:
int_arr = np.array([1, 2, 3])
print(int_arr.dtype)

int64


In [ ]:
str_arr = np.array(['a', 'b', 'c'])
print(str_arr.dtype)

<U1


In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr)

[1. 2. 3.]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.ndim)

2


In [ ]:
print(arr.shape)

(2, 4)


In [ ]:
print(arr.size)

8


In [ ]:
print(arr.dtype)

int64


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Addition
print(arr + 10)
# Output: [11 12 13 14 15]

# Subtraction
print(arr - 2)
# Output: [-1  0  1  2  3]

# Multiplication
print(arr * 3)
# Output: [ 3  6  9 12 15]

# Division
print(arr / 2)
# Output: [0.5 1.  1.5 2.  2.5]

# Power
print(arr ** 2)
# Output: [ 1  4  9 16 25]

# Modulus
print(arr % 2)
# Output: [1 0 1 0 1]

[11 12 13 14 15]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1 0 1 0 1]


In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Element-wise operations
print(mat1 + mat2)
# Output:
# [[ 6  8]
#  [10 12]]

[[ 6  8]
 [10 12]]


In [ ]:
print(mat1 * mat2)  # Element-wise multiplication
# Output:
# [[ 5 12]
#  [21 32]]

[[ 5 12]
 [21 32]]


In [ ]:
# Matrix multiplication (dot product)
print(np.dot(mat1, mat2))
# Output:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))        # 15
print(arr.sum())          # 15 (method syntax)
print(np.mean(arr))       # 3.0
print(np.std(arr))        # 1.4142135623730951 (standard deviation)
print(np.var(arr))        # 2.0 (variance)
print(np.min(arr))        # 1
print(np.max(arr))        # 5
print(np.argmin(arr))     # 0 (index of minimum)
print(np.argmax(arr))     # 4 (index of maximum)

15
15
3.0
1.4142135623730951
2.0
1
5
0
4


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d.sum())              # 21 (sum of all elements)
print(arr_2d.sum(axis=0))        # [ 5  7  9] (sum along rows - column sums)
print(arr_2d.sum(axis=1))        # [ 6 15] (sum along columns - row sums)

print(arr_2d.mean(axis=0))       # [2.5 3.5 4.5]
print(arr_2d.max(axis=1))        # [3 6]

21
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]
[3 6]


# Edge

In [ ]:
arr = np.array([1, 2, 3])
result = arr / 0
print(result)

[inf inf inf]


/tmp/ipython-input-976154894.py:2: RuntimeWarning: divide by zero encountered in divide
  result = arr / 0


In [ ]:
arr = np.array([0, 1, 2])
result = arr / arr
print(result)

[nan  1.  1.]


/tmp/ipython-input-1047412984.py:2: RuntimeWarning: invalid value encountered in divide
  result = arr / arr


In [ ]:
print(np.isinf(arr_1d = np.array([1, 2, 3, 4])
print(arr_1d.shape)))
print(np.isnan(result))

[False False False]
[ True False False]


In [ ]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d.shape)

(4,)


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.shape)

(2, 2, 2)


In [ ]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr_2d = arr.reshape(3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr_2d = arr.reshape(2, 6)
print(arr_2d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
arr_3d = arr.reshape(2, 3, 2)
print(arr_3d)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
arr = np.arange(538)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
arr_2d = arr.reshape(1, -1)  # 4 rows, auto-calculate columns
print(arr_2d.shape)

(1, 24)


In [ ]:
arr = np.arange(24)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
arr = np.arange(24)

# Use -1 to automatically calculate one dimension
arr_2d = arr.reshape(4, -1)  # 4 rows, auto-calculate columns
print(arr_2d.shape)
# Output: (4, 6)

arr_2d = arr.reshape(-1, 8)  # auto-calculate rows, 8 columns
print(arr_2d.shape)
# Output: (3, 8)


(4, 6)
(3, 8)


In [ ]:
arr.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d.reshape(2,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Method 1: flatten (returns a copy)
flat1 = arr_2d.flatten()
print(flat1)
# Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [ ]:
flat1 = arr_2d.ravel()
print(flat1)

[1 2 3 4 5 6]


In [ ]:
flat3 = arr_2d.reshape(-1)
print(flat3)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
flat_flatten = arr.flatten()
print(flat_flatten)

[1 2 3 4]


In [ ]:
import numpy as np
import time

# Create large data
size = 1000000

python_list = list(range(size))
numpy_array = np.arange(size)

# Test 1: Summing elements
# Python list
start = time.time()
total = sum(python_list)
print(total)
python_time = time.time() - start

# NumPy array
start = time.time()
total = np.sum(numpy_array)
print(total)
numpy_time = time.time() - start

print(f"Python list sum: {python_time:.5f} seconds")
print(f"NumPy array sum: {numpy_time:.5f} seconds")
print(f"NumPy is {python_time/numpy_time:.1f}x faster")

499999500000
499999500000
Python list sum: 0.01026 seconds
NumPy array sum: 0.00124 seconds
NumPy is 8.3x faster


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
transposed = arr.T
print(transposed)
print(transposed.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)
